// <auto-generated />
using System;
using EFCoreProjetoFinal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreProjetoFinal.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231212230150_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EFCoreProjetoFinal.Domain.CodigoAcesso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("DataAtivacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Codigos");
                });

            modelBuilder.Entity("EFCoreProjetoFinal.Domain.Estudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Estudios", (string)null);
                });

            modelBuilder.Entity("EFCoreProjetoFinal.Domain.Genero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Generos", (string)null);
                });

            modelBuilder.Entity("EFCoreProjetoFinal.Domain.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoAcessoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("EstudioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GeneroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("PlataformaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAcessoId");

                    b.ToTable("Jogos", (string)null);
                });

            modelBuilder.Entity("EFCoreProjetoFinal.Domain.Plataforma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Plataformas", (string)null);
                });

            modelBuilder.Entity("EstudioJogo", b =>
                {
                    b.Property<Guid>("EstudioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JogosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EstudioId", "JogosId");

                    b.HasIndex("JogosId");

                    b.ToTable("EstudioJogo");
                });

            modelBuilder.Entity("GeneroJogo", b =>
                {
                    b.Property<Guid>("GeneroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JogosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GeneroId", "JogosId");

                    b.HasIndex("JogosId");

                    b.ToTable("GeneroJogo");
                });

            modelBuilder.Entity("JogoPlataforma", b =>
                {
                    b.Property<Guid>("JogosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlataformaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JogosId", "PlataformaId");

                    b.HasIndex("PlataformaId");

                    b.ToTable("JogoPlataforma");
                });

            modelBuilder.Entity("EFCoreProjetoFinal.Domain.Jogo", b =>
                {
                    b.HasOne("EFCoreProjetoFinal.Domain.CodigoAcesso", "CodigoAcesso")
                        .WithMany("Jogos")
                        .HasForeignKey("CodigoAcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodigoAcesso");
                });

            modelBuilder.Entity("EstudioJogo", b =>
                {
                    b.HasOne("EFCoreProjetoFinal.Domain.Estudio", null)
                        .WithMany()
                        .HasForeignKey("EstudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreProjetoFinal.Domain.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeneroJogo", b =>
                {
                    b.HasOne("EFCoreProjetoFinal.Domain.Genero", null)
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreProjetoFinal.Domain.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JogoPlataforma", b =>
                {
                    b.HasOne("EFCoreProjetoFinal.Domain.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreProjetoFinal.Domain.Plataforma", null)
                        .WithMany()
                        .HasForeignKey("PlataformaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCoreProjetoFinal.Domain.CodigoAcesso", b =>
                {
                    b.Navigation("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
